apiVersion: v1
kind: Service
metadata:
  name: vkuserandgroup-app-service
spec:
  selector:
    app: vkuserandgroup-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: LoadBalancer